[package]
name = "cnj-scraper"
version = "0.1.0"
authors = ["Bruno Arueira <contato@brunoarueira.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
time = "*"
itertools = "*"
